kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-config
  namespace: dev-namespace

data:
  SERVER_PORT: "8080"

  APP_MESSAGE: "Hello from DEV"

  DB_URL: "jdbc:h2:mem:testdb"

  DB_USERNAME: "sa"

  LOG_LEVEL: "DEBUG"