kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-deployment
  namespace: dev-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app

    spec:
      containers:
        - name: dev-springboot-container
          image: xyz
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: dev-config

            - secretRef:
                name: dev-secret
