apiVersion: apps/v1
kind: Deployment

metadata:
  name: dev-deployment
  namespace: dev-namespace

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: product-app

  template:
    metadata:
      labels:
        app: product-app

    spec:
      containers:
        - name: dev-springboot-container
          image: rohitkumar4praja/product-app:v3

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: dev-config

            - secretRef:
                name: dev-secret

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /api/products
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/products
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
