kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: dev-namespace

spec:
  selector:
    app: product-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30080

  type: ClusterIP