name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build Spring Boot Jar
        run: |
          cd Shristi
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./Shristi
          push: true
          tags: |
            rohitkumar4praja/product-app:latest
            rohitkumar4praja/product-app:v3
            rohitkumar4praja/product-app:${{ github.sha }}

  build-and-push-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./product-frontend
          push: true
          tags: |
            rohitkumar4praja/frontend-product:latest
            rohitkumar4praja/frontend-product:v4
            rohitkumar4praja/frontend-product:${{ github.sha }}
